name = "url-resolver"
compatibility_date = "2025-26-03"
main = "index.js"

[vars]
FACEBOOK_UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

[env.production]
workers_dev = true